

                                                                                
                                                                                
                                                                                                                        
                                                                                                                
                                                                                                                                                            
                                                                                                                                                                        
                                                                                                                                
                                                                                                                                                                        
                                                                                                                                                                                                    } else if (command[i] == "empty") {
                                                                                                                                                                                                                cout << (s.empty() ? 1 : 0) << endl;
                                                                                                                                                                                                                        } else if (command[i] == "top") {
                                                                                                                                                                                                                                    if (s.empty()) {
                                                                                                                                                                                                                                                    cout << -1 << endl;
                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                cout << s.top() << endl;
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                            return 0;
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            #include <iostream>
                                                                                                                                                                                                                                                                                                            #include <stack>
                                                                                                                                                                                                                                                                                                            using namespace std;

                                                                                                                                                                                                                                                                                                            int N;
                                                                                                                                                                                                                                                                                                            string command[10000];
                                                                                                                                                                                                                                                                                                            int value[10000];

                                                                                                                                                                                                                                                                                                            int main() {
                                                                                                                                                                                                                                                                                                                cin >> N;
                                                                                                                                                                                                                                                                                                                    for (int i = 0; i < N; i++) {
                                                                                                                                                                                                                                                                                                                            cin >> command[i];
                                                                                                                                                                                                                                                                                                                                    if (command[i] == "push") {
                                                                                                                                                                                                                                                                                                                                                cin >> value[i];
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                stack<int> s;
                                                                                                                                                                                                                                                                                                                                                                    for (int i = 0; i < N; i++) {
                                                                                                                                                                                                                                                                                                                                                                            if (command[i] == "push") {
                                                                                                                                                                                                                                                                                                                                                                                        s.push(value[i]);
                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                        

